spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/bloglib?useSSL=false&serverTimezone=UTC
    username: root
    password: testformat

author: A.Danilov