spring:
  flyway:
    enabled: false
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bloglib?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: -1  #Makes handling file size on a controller level
      max-request-size: -1
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: app.autosender@gmail.com
    password: 17122020Dec!$

mail:
  debug: false   #Disable in production!

#Captcha service properties
captcha:
  expiration-time: 3600 #seconds
  image:
    url: data:image/png;base64
    height: 35
    width: 100
    format: png

#Like service properties
vote:
  like-value: 1
  dislike-value: -1

#File upload service properties
file:
  max-file-size: 5 #MB
  max-image-height: 36 #px
  max-image-width: 36 #px
  upload-directory: upload

#Application values
photo:
  delete-value: 1

root-domain: http://localhost:8080