spring:
  flyway:
    enabled: false
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/bloglib?useSSL=false&serverTimezone=UTC
    username: root
    password: testformat


author: A.Danilov