create table captcha_codes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(255) not null,
    secret_code VARCHAR(255),
    time        TIMESTAMPTZ not null,
    primary key (id)
);

create table global_settings
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code  VARCHAR(255) not null,
    name  VARCHAR(255) not null,
    value VARCHAR(255) not null,
    primary key (id)
);

create table post_comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parent_id BIGINT,
    post_id   BIGINT not null,
    text      TEXT    not null,
    time      TIMESTAMPTZ not null,
    user_id   BIGINT not null,
    primary key (id)
);

create table post_votes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT not null,
    time    TIMESTAMPTZ not null,
    user_id BIGINT not null,
    value   INTEGER not null,
    primary key (id)
);

create table posts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_active         INTEGER                   not null,
    moderation_status VARCHAR(32) default 'NEW' not null,
    moderator_id      BIGINT,
    text              TEXT                      not null,
    time              TIMESTAMPTZ not null,
    title             VARCHAR(255)              not null,
    user_id           BIGINT                   not null,
    view_count        INTEGER                   not null,
    primary key (id)
);

create table tag2post
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT not null,
    tag_id  BIGINT not null,
    primary key (id)
);

create table tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) not null,
    primary key (id)
);

create table users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code         VARCHAR(255),
    email        VARCHAR(255) not null,
    is_moderator INTEGER      not null,
    name         VARCHAR(255) not null,
    password     VARCHAR(255) not null,
    photo        TEXT,
    reg_time     TIMESTAMPTZ not null,
    primary key (id)
);
